### ISSUE TITLE
멀티 리스너를 사용 할 때 기본 리스너의 ID 고정 방법 문의

### ISSUE THREAD

**Issue by dethjuni-gm** [pdpdds/CGSF#19]
ServerListener 프로젝트의 샘플을 이용했습니다.

SFEngine::GetInstance()->AddListener 를 이용하여 리스너를 추가할 때 마다
EngineConfig.xml에서 정의한 기본 port를 이용하는 리스너의 SessionID가 계속 밀리는 현상이 있습니다.

예를 들어 AddListener 를 사용 하지 않을 때의 기본 포트의 SessionID는 1이지만
AddListener 를 한 번 사용 한 경우 기본 포트의 SessionID는 2가 됩니다.
AddListener 를 두 번 사용 한 경우 기본 포트의 SessionID는 3이 됩니다.

기본 port의 ID를 고정 시킬 수 있는 방법이 있는지 궁금합니다.

**Comment by pdpdds** [comment]
기본 리스너의 세션아이디를 고정시키는게 좋을 것 같습니다. 수정하겠습니다.

**Comment by pdpdds** [comment]
기본 서버 리스너의 아이디를 고정시켰습니다. 무조건 1로 설정되게 했으니 업데이트 받으셔서 확인 부탁드리겠습니다.

**Comment by dethjuni-gm** [comment]
이번에 변경 내용이 꽤 많네요.
수고 많으십니다. ^^

기본 서버 리스너 아이디 고정 잘 동작합니다.

좀 더 테스트 해보겠습니다.
