### ISSUE TITLE
C# 컴파일에 문제가 있습니다.

### ISSUE THREAD

**Issue by danaka1234** [pdpdds/CGSF#20]
버전은 현재 최신 버전에서 Realese에 있는 ThirdParty를 닷넷 폴더에 추가.

> CgsfNET64LibProject 컴파일시
GetNetworkEngine 함수가 private라서 오류가 뜨길래 public으로 이동.

> CGSFNETCommon 컴파일 시
NLog는 어떻게 xsd 프로그램을 이용해서 cs파일을 만들었는데
이하의 오류들은 어떻게 안되네요; 원래 이런것인지 확인 부탁드립니다.

경고	7	참조된 구성 요소 'Sigil'을(를) 찾을 수 없습니다. 
경고	6	참조된 구성 요소 'NLog'을(를) 찾을 수 없습니다. 
경고	5	참조된 구성 요소 'Jil'을(를) 찾을 수 없습니다. 
경고	3	이 참조를 확인할 수 없습니다. "Sigil" 어셈블리를 찾을 수 없습니다. 어셈블리가 디스크에 있는지 확인하십시오. 해당 코드에 이 참조가 필요한 경우 컴파일 오류가 발생할 수 있습니다.
경고	2	이 참조를 확인할 수 없습니다. "NLog" 어셈블리를 찾을 수 없습니다. 어셈블리가 디스크에 있는지 확인하십시오. 해당 코드에 이 참조가 필요한 경우 컴파일 오류가 발생할 수 있습니다.
경고	1	이 참조를 확인할 수 없습니다. "Jil" 어셈블리를 찾을 수 없습니다. 어셈블리가 디스크에 있는지 확인하십시오. 해당 코드에 이 참조가 필요한 경우 컴파일 오류가 발생할 수 있습니다.
오류	9	'LogManager' 이름이 현재 컨텍스트에 없습니다.	D:\projects\CGSF\CGSF-master\NETFramework\CGSFNETCommon\FileLogger.cs	13
오류	4	'Logger' 형식 또는 네임스페이스 이름을 찾을 수 없습니다. using 지시문 또는 어셈블리 참조가 있는지 확인하십시오.	D:\projects\CGSF\CGSF-master\NETFramework\CGSFNETCommon\FileLogger.cs	13
오류	8	'CGSFNETCommon.FileLogger.Logger'은(는) '필드'이지만 '형식'처럼 사용됩니다.	D:\projects\CGSF\CGSF-master\NETFramework\CGSFNETCommon\FileLogger.cs	13

**Comment by danaka1234** [comment]
Sigil NLog Jil 각 라이브러리를 ThirdParty에 설치해야 하나요?

**Comment by jacking75** [comment]
Sigil NLog Jil
위의 라이브러리들은 비주얼스튜디어의 NuGet으로 설치하는 외부 라이브러리입니다.
CGSFNETCommon 프로젝트만 따로 열어서 재빌드 해보세요. 아마 NuGet이 자동으로 다운로드 할 것입니다.
(만약 NuGet 버전이 예전 것이라면 업데이트 해주세요)
NuGet이 자동으로 해주지 않는다면 직접 NuGet에서 설치하시기 바랍니다.



2015-01-14 21:57 GMT+09:00 danaka1234 <notifications@github.com>:

> Sigil NLog Jil 각 라이브러리를 ThirdParty에 설치해야 하나요?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pdpdds/CGSF/issues/20#issuecomment-69912196>.
>



-- 
Twitter : @jacking75
Blog : http://jacking.tistory.com/

**Comment by jacking75** [comment]
NuGet에 관한 것은 아래 글 참조 바랍니다.
http://blog.danggun.net/1741
http://shyjoo.tistory.com/44
http://nsinc.tistory.com/107

**Comment by danaka1234** [comment]
NuGet 재설치해서 해결했습니다.
