### ISSUE TITLE
안녕하세요. 튜토리얼 관련해서 올려봅니다.

### ISSUE THREAD

**Issue by angeluen** [pdpdds/CGSF#22]
안녕하세요. 최근 CGSF를 배우고있는 학생입니다.

우선 개발에 관련된 이슈가 아니라 죄송합니다.

다름이 아니라 CGSF를 통해 게임을 개발할려고합니다. 

새프로젝트를 만들려고 하는데 CGSF라이브러리가 담긴 빈 새 프로젝트를 만드는 방법을 잘 모르겠습니다.

책을 포함 관련 문서를 찾아보는데 찾을 수가 없었네요.

그리고 새프로젝트를 기존 책에있던 코드가 아닌 현재 업데이트 해주신 코드를 바탕으로 할려고 합니다.

올려주신 서드파티를 이어 주려고 합니다만, 실력이 모잘라 정확한 방법을 모르겠습니다.

혹시 새 프로젝트를 만드는 방법과 함께 기존 깃허브에있는 코드를 서드파티에 연결해주는 관련 문서를 추가 해주실 수 있으신가요??

**Comment by pdpdds** [comment]
콘솔 프로젝트를 생성하고 에코 서버 프로젝트를 참조해서 포함 파일 폴더와 라이브러리 포함 경로를 지정해 주시면 됩니다. 서드파티는 CGSF 첫화면의 External  링크에서 다운받으신 뒤(ThridParty.rar)  CGSF 소스의 루트 폴더에서 압축을 푸시면 됩니다. 비쥬얼 스튜디오에 익숙치 못해서 질문주신거라면 별도의 문서를 만들거나 동영상 파일로 만들어서 CGSF 기본 골격 프로젝트를 생성하는 방법을 정리해서 알려드리겠습니다.

**Comment by angeluen** [comment]
늦은밤 답변 정말 감사합니다.

답변해주신 내용을 바탕으로 열심히 해보도록 하겠습니다.

그리고 혹시 실례가 안된다면 나중에 자세히 참고 할 수 있도록 문서작성을 부탁드리겠습니다.

감사합니다.

**Comment by pdpdds** [comment]
프로젝트 생성 부분에 대해서는 직접 해보시는게 큰 도움이 될 것입니다. 잘안되면 코멘트 남겨주세요. 간단한 튜토리얼을 제작하겠습니다.

**Comment by angeluen** [comment]
말씀해주신대로 EchoServer 프로젝트를 참조해서 포함 파일 폴더와 라이브러리 포함 경로를 지정해 주었는데 아무런 라이브러리가 적용 되지 않네요. 아마 제가 비주얼 스튜디오를 잘 못다루는것 같습니다.

**Comment by pdpdds** [comment]
Doc 폴더에 CGSF 기본 프로젝트 생성 문서를 추가했습니다. 받아서 프로젝트를 생성해 보시고 막히는 부분 있으면 알려주시기 바랍니다.

**Comment by angeluen** [comment]
감사합니다. 친절하게 적어주신대로 하니 프로젝트가 잘 생성되네요!!
