### ISSUE TITLE
혹시 MFC 지원하나요?

### ISSUE THREAD

**Issue by BornHunter** [pdpdds/CGSF#25]
혹시 MFC 지원하는지 궁금합니다.
그냥 mfc포함안한 윈도 콘솔로만 사용해야 되는지요?

**Comment by jacking75** [comment]
MFC를 사용해보지 않았는데 딱히 문제될 것은 없습니다.
한번 해보시고 문제 있으면 알려주세요^^;

**Comment by dethjuni-gm** [comment]
제가 콘솔에서 CGSF와 MFC를 같이 사용 하고 있습니다.
문제 없습니다.

**Comment by BornHunter** [comment]
네 답변감사드립니다.^^
