### ISSUE TITLE
Google Protocol Buffer 질문입니다.

### ISSUE THREAD

**Issue by BornHunter** [pdpdds/CGSF#26]
패킷으로 Protocol Buffer를 사용할려고 하는데요
2번째 책에 있는 
"3.3 CGSFPacketProtocol 패킷 가공" 챕터부분 내용을
직접 구현해야 되는건가요?(패킷 뭉침, 잘림, 암호화등등 처리)
아니면 다 구현되어 있어서 그냥 proto 파일만 만들어서 사용하면 되는건가요?

**Comment by pdpdds** [comment]
proto 파일만 만들어서 사용하면 됩니다. 1권의 세븐 게임과 FPS 게임 프로젝트가  프로토콜 버퍼를 사용하니 참조하세요.

**Comment by BornHunter** [comment]
네 답변 감사드립니다.
