### ISSUE TITLE
차후 업데이트 예정이 있나요?

### ISSUE THREAD

**Issue by BornHunter** [pdpdds/CGSF#27]
CGSF엔진으로 상용서버 개발 예정인데요 게임은 아니고요;;
혹시 차후 현재 소스대비 크게 변경사항이 있다거나 업데이트 예정이 있는지 궁금합니다.

**Comment by pdpdds** [comment]
CGSF는 계속해서 기능을 추가하고 업데이트할 예정에 있습니다.
당분간은 개인적인 사정때문에 CGSF의 대폭적인 업데이트는 없겠지만
문의사항에 대해서는 언제든지 답변드릴 수 있으니 글남겨 주시기 바랍니다.
추후 CGSF에 큰 수정이 있다하더라도 인터페이스에 큰 변화는 없을 것이기 때문에
지금 버전으로 서버를 개발한후 나중에 업데이트된 내용을 적용하면 될것입니다.

CGSF를 사용하시다가 건의사항이나 에러 등을 알려주시면 적극 반영하겠습니다.

**Comment by BornHunter** [comment]
네 답변 감사드립니다.
