### ISSUE TITLE
SFMSSQLAdaptor 사용법 질문드립니다.

### ISSUE THREAD

**Issue by BornHunter** [pdpdds/CGSF#28]
MS SQL 사용해야해서 CGSFTest 폴더에있는 Database 예제를 보고있는데요
SFMSSQLAdaptor 사용법이 조금 생소해서 질문드립니다.
MySql 같은 경우 쿼리문 문자열 만들어 넘겨서 하는 방식이던데  
MS SQL은 SFStatement라는 클래스 사용해서 쿼리를 하는거같은데요
select, update, delete 예제나 사용법 좀 부탁드립니다.
복잡한 쿼리문 같은경우는 어떻게 해야되는지;;

**Comment by pdpdds** [comment]
SFMSSQLAdaptorImpl 클래스를 살펴보면 사용법을 확인할 수 있습니다. 복잡한 쿼리문의 경우에는 Stored Procedure 를 작성해서 응용 프로그램에서 DB의 SP를 호출하면 됩니다.

**Comment by BornHunter** [comment]
사용법좀 익힐려면 테스트 많이 해봐야 겠네요
