### ISSUE TITLE
테스트중 발견한 이슈 사항입니다.

### ISSUE THREAD

**Issue by BornHunter** [pdpdds/CGSF#31]
테스트중 발견한 이슈 사항입니다.

(1) 서버간 연결 테스트중 발견한 사항입니다.
ServerListener, ServerConnector 예제 참고하여 테스트 해봤는데

SFServerConnectionManager 클래스에
m_hThread = (HANDLE)_beginthreadex(0, NULL, ServerReconnectProc, this, 0, (unsigned*)&m_dwThreadID); 부분에서
스레드 생성후 서버 종료시 스레드 종료전에 m_listConnectorInfo가 먼져 삭제되어
포인트 오류 발생합니다.(디버그 모드로 실행 후 종료시)
delete m_pServerConnectionManager; 코드전에 스레드 종료해줘야 할거 같습니다.

(2) 서버 프로그램 서비스 등록 후 종료시 이슈 입니다.
SevenGameServer 예제 보고서 서비스 등록 테스트 해봤는데
등록, 삭제등 모두 잘 동작하는데 윈도우 서비스 관리자에서 서비스 중시지
정상 종료 되지 않고 0byte 덤프발생하면서 종료 됩니다.(SFBreakPad)
서비스가 아닌 그냥 로컬에서 실행하면 종료 로그 다 찍히면서 종료되고요
디버그 해보니 ACE_Thread_Manager::instance()->wait_grp 이분에서 덤프 발생하면서 
강제 종료 됩니다.

테스트하다 발견한건데 혹시 참고가 될까 올립니다.

**Comment by pdpdds** [comment]
확인해 보겠습니다.

**Comment by pdpdds** [comment]
(1) 객체 제거시 스레드 종료 루틴을 추가 했습니다.
(2) 디버그/릴리스 모드에서는 아무런 문제가 없는데 윈도우 서비스로 동작시 ACE 모듈과 충돌을 일으키는 것 같습니다. 말씀하신대로 ACE의 스레드 매니저 기능을 사용하지 않으면 문제가 발생하지 않지만 또다른 부분에서 문제가 발생하는 만큼(ACE 모듈 해제) 시간을 두고 좀 더 살펴보겠습니다.

**Comment by pdpdds** [comment]
(2) ACE 모듈의 초기화 및 종료는 메인 스레드에서 수행해야 하는데 별도의 스레드에서 초기화 및 종료를 하면서 문제가 발생하였습니다. SevenGameServer.cpp  파일을 보면 수정사항을 확인하실 수 있습니다.

**Comment by pdpdds** [comment]
(2) 확인결과 서비스 제어 매니저(SCM)을 사용하는 부분에 문제가 있었습니다. 문제 해결을 위해 SCM 제어 코드를 심플하게 변경하였습니다. 테스트 해주시면 감사하겠습니다.

**Comment by BornHunter** [comment]
수정하신 내용 모두 정상 동작 합니다. 감사합니다.
