### ISSUE TITLE
google glog 질문드립니다.

### ISSUE THREAD

**Issue by BornHunter** [pdpdds/CGSF#46]
안녕하세요
CGSF엔진에서 사용중인 google glog 관련 질문이 있습니다.
로그를 일단위로 생성하고 싶은데 glog에서는 지원하지 않는건가요?
인터넷에 찾아보니 지원하지 않는거 같던데
일단위로 로그를 남길려면 다른 라이브러리를 이용해야 하는지요?

추가로 CGSF엔진으로 개발이 거의 마무리되어 서비스를 준비중에 있습니다.
(게임이 아닌 기업용 프로그램입니다.)
혹시 주의 해야 할 사항 같은건 없는지 궁금하네요

**Comment by pdpdds** [comment]
혹시 온라인 게임 서버 카페에 질문 남기셨는지요. 아마도 glog 소스를 수정해서 일단위로 변경하시거나 해당 기능이 꼭 필요하다면 다른 로그라이브러리를 사용해도 괜찮을 듯 합니다.

아직 CGSF를 사용해서 서비스를 시작한 프로젝트가 없는데 이게 최초네요. 저도 CGSF를 사용해서 모바일 게임을 개발하고 있는데 내년중에 출시될 예정이라 해당 모듈에 대한 엄중한 테스트가 필요할 것 같습니다.

충분히 테스트를 하셨는지 궁금하구요, 혹 문제가 발생한다면 제게 연락을 주시면 찾아가서 봐드릴 수 있으니 언제든지 말씀해 주세요. 해당 소프트웨어가 문제없이 동작하기를 진심으로 바라고 있습니다.

궁금한 점은
1. 기업 사내 시스템을 위한 소프트웨어로  CGSF를 활용하셨나요? 예상 최대 동접은 얼마나 생각하시나요?
2. 채팅서버같이 단순한 용도로 사용하셨나요, 아님 실시간 게임처럼 패킷을 재빨리 교환하는 용도로 사용하셨는지요.
3. 부하테스트나 소켓 연결 및 끊기 등의 QA를 진행하셨는지.

위의 질문에 대한 답변에 따라 크게 문제는 없을 듯 합니다만 혹 문제가 발생하면 앞에서도 언급했지만 제가 찾아가서 봐드릴 수 있으니 언제든지 연락주세요.

그럼 좋은 하루 되시기 바랍니다.

**Comment by BornHunter** [comment]
게임 개발자가 아니라서 게임 서버 카페에는 가입되어 있지 않네요
예전에 한번 가입해봤는데 게임쪽 현업이 아니라 정리된 기억이..;;

프로그램은 기업용 메신저 입니다. (기존 서비스 중인 메신저 대체)
카톡이나 라인같은 메시지를 DB에 일정기간 저장하는 톡방식으로 만들었습니다.
현재 예상 유저수는 10만명 정도 이고요 PC, 모바일 둘다 지원합니다.
TCP만 사용하고 프로토콜은 json포맷 사용했습니다.
제가 서버랑 PC쪽을(MFC) 맡아서 개발했고요
만일 프로그램 오류없이 잘 동작한다는 가정하에 동접수는 5만이상될거 같습니다.
(전체 동접은 5만이상이지만 서버프로세스당 5000이하)

서버는 인증 및 대화와 관련된 작업만 처리합니다. (인증, 메시지 전송, 푸시, DB처리)
기타 다른 정보는 web api를이용 합니다.
현재 구성은 CGSF엔진 디폴트 유저 접속 허용 수가 5000 으로 되어 있어서
프로세스당 세션 4096정도로 잡아서 구성했고 회사단위로 서버 프로세스를 
나누어서 처리하는 방식으로 했습니다.(DB는 하나)
(예: A회사 100명, B회사 1000명, C회사 3000명이면 A,B회사는 1번 서버프로세스로 접속
 C회사는 2번 서버프로세스로 접속)
향후 인원이 많은 회사의 경우를 위해 서버 프로세스를 그룹으로 묶어서 처리 할려고 하는데
서버 프로세스간 동기화 문제를 어떻게 처리해야 할지 고민중입니다. 

아직 부하 테스트는 진행하지 못했습니다.
성능 테스트는 일단 여러가지 여건상 베타 테스트 형식으로 할 계획입니다.
테스트 신청한 회사들을 서버 프로세스 하나에 최대한 모아서 테스트 할 생각입니다.
테스트 결과에 따라 서버프로세스당 접속자 수도 정해질거 같습니다.

저도 유지보수만 주로 하다 처음부터 만들어본건 이번이 처음이라 걱정이 많네요;;

답변 감사드립니다.

**Comment by jacking75** [comment]
안녕하세요^^
게임 서버 카페는 예전에는 서버 개발자만 등급을 올려주었는데 지금은 현업 개발자면 누구나 등급을 올려줍니다. 
그러니 아직 가입 신청을 하지 않으셨다면 가입신청 후 가입 인사를 하시면 됩니다.

제가 알기로는 CGSF를 처음으로 상용 서비스에 사용하는 것이라서 관심이 많아서 제가 도와 드릴 것이 있으면 도와 드리고 싶습니다^^
저는 판교에 있는데 혹시 판교쪽에 계시면 제가 도와 드릴 것이 있으면 연락주세요~

**Comment by BornHunter** [comment]
네 회사는 강남인데 문제 생기면 찾아가서라도 조언구하겠습니다. ^^;

**Comment by pdpdds** [comment]
현재 제 출퇴근 경로에 강남역이 있어요 ^^ jacking75님도 강남역을 환승하시니 언제든지 불러주시면 찾아갈 준비가 되어 있습니다. 부담갖지 마시고 문제가 발생하면 언제든지 연락주세요~
