### ISSUE TITLE
CGSF 빌드를 하면 zdb.h, sqlite3.h, SDL.h, SDL_net.h 등의 파일을 찾을 수 없다고 나옵니다.

### ISSUE THREAD

**Issue by FortheAllianceMagician** [pdpdds/CGSF#52]
먼저 책에 나와있는대로 환경 설정 및 thirdparty 그리고 boost_1_55_0와 Microsoft DirectX SDK (June 2010)도 설치하였습니다.

이후 AllProject.sln로 CGSF를 전체 빌드하면,

..\VSProject\Lib\x86\Debug 폴더에 BaseLayer.lib, CasualGame.lib, CasualGameGUI.lib, CommonLayer.lib, FPSEngine.lib는 잘 생성되었으나 나머지 .lib 파일들은 위 제목의 에러들이 나타나면서 생성이 되지 않고있습니다.

제가 어떤걸 놓치고 있는지 도저히 감이 오지않아 여기에 문의드립니다.

error 내용
Error	1	error C1083: Cannot open include file: 'zdb.h': No such file or directory
Error	3	error C1083: Cannot open include file: 'sqlite3.h': No such file or directory
Error	4	error C1083: Cannot open include file: 'SDL.h': No such file or directory
Error	5	error C1083: Cannot open include file: 'http.hpp': No such file or directory
Error	7	error C1083: Cannot open include file: 'avro/Encoder.hh': No such file or directory
Error	9	error C1083: Cannot open include file: 'zmq.hpp': No such file or directory
Error	10	error C1083: Cannot open include file: 'SDL_net.h': No such file or directory

**Comment by BornHunter** [comment]
프로젝트 옵션에서 **추가 포함 디렉터리, 추가 라이브러리 디렉터리등**에 ThirdParty 경로가 정확한지 확이해보세요

**Comment by FortheAllianceMagician** [comment]
현재 GitHub에 있는 CGSF 최신버전을 다운받았었는데, 위와같은 문제가 있어서

혹시 몰라 readme.md 파일에 명시된
* [CGSF External] (https://drive.google.com/folderview?id=0B4zZS0o3dor0ZGswUU9uT1RsUVE&usp=sharing)
에서 다운받아 책 내용대로 해봤더니 잘 됩니다.

감사합니다. ^^
