### ISSUE TITLE
라이선스 문의 드립니다.

### ISSUE THREAD

**Issue by Knext** [pdpdds/CGSF#57]
CGSF의 CrashHandler 구현 부분을 사용하고 싶은데요. 

https://github.com/pdpdds/CGSF/blob/master/BaseLayer/CrashHandler.cpp

별도의 라이선스등이 명시되어 있지 않아서 문의 드립니다.
다른 프로젝트에서 사용해도 되는지요?

**Comment by pdpdds** [comment]
네 상관없이 사용하셔도 됩니다.

**Comment by Knext** [comment]
네 확인 고맙습니다~
